export const STATUS_IN_PROGRESS    = 'IN_PROGRESS';
export const STATUS_SUCCESS        = 'SUCCESS';
export const STATUS_FAILURE        = 'FAILURE';
export const STATUS_REMOTE_ORIGIN  = 'REMOTE_ORIGIN';

export const FETCH_CONVERSATION_OBJECTS = 'FETCH_CONVERSATION_OBJECTS';

export const CREATE_DELIVERABLE = 'CREATE_DELIVERABLE';
export const UPDATE_DELIVERABLE = 'UPDATE_DELIVERABLE';
export const FETCH_DELIVERABLE = 'FETCH_DELIVERABLE';

export const CREATE_AGENDA_ITEM = 'CREATE_AGENDA_ITEM';
export const UPDATE_AGENDA_ITEM = 'UPDATE_AGENDA_ITEM';
export const FETCH_AGENDA_ITEM = 'FETCH_AGENDA_ITEM';
