export const STATUS_IN_PROGRESS    = 'IN_PROGRESS';
export const STATUS_SUCCESS        = 'SUCCESS';
export const STATUS_FAILURE        = 'FAILURE';
export const STATUS_REMOTE_ORIGIN  = 'REMOTE_ORIGIN';

export const DELETE = 'DELETE';
export const FETCH_CONVERSATION_OBJECTS = 'FETCH_CONVERSATION_OBJECTS';

export const CREATE_DELIVERABLE = 'CREATE_DELIVERABLE';
export const UPDATE_DELIVERABLE = 'UPDATE_DELIVERABLE';
export const FETCH_DELIVERABLE = 'FETCH_DELIVERABLE';

export const CREATE_AGENDA_ITEM = 'CREATE_AGENDA_ITEM';
export const UPDATE_AGENDA_ITEM = 'UPDATE_AGENDA_ITEM';
export const FETCH_AGENDA_ITEM = 'FETCH_AGENDA_ITEM';

export const SET_UNSEEN_OBJECTS = 'SET_UNSEEN_OBJECTS';
export const CREATE_UNSEEN_OBJECT = 'CREATE_UNSEEN_OBJECT';
export const DELETE_UNSEEN_OBJECTS = 'DELETE_UNSEEN_OBJECTS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USERS = 'SET_USERS';
export const UPDATE_USER = 'UPDATE_USER';

export const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';

export const INVITE_ORGANIZATION_MEMBER = 'INVITE_ORGANIZATION_MEMBER';
export const CREATE_ORGANIZATION_MEMBER = 'CREATE_ORGANIZATION_MEMBER';
export const DELETE_ORGANIZATION_MEMBER = 'DELETE_ORGANIZATION_MEMBER';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const CREATE_CONVERSATION_MEMBER = 'CREATE_CONVERSATION_MEMBER';
export const DELETE_CONVERSATION_MEMBER = 'DELETE_CONVERSATION_MEMBER';

export const CONVERSATION = 'CONVERSATION';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

export const SET_CONVERSATION_SETTINGS_STATE = 'SET_CONVERSATION_SETTINGS_STATE';
export const RESET_CONVERSATION_UI = 'RESET_CONVERSATION_UI';

export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';

export const ROUTE_LOCATION_UPDATE = '@@router/UPDATE_LOCATION';