# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af6ab5e41e46294cf042454ca50b964dd0f3031306fa7b890ce29f95c7f8396e276f4a6d30fce3d987cb0d5ac22dbefa841b23b54b2f20179b0e55fed2a39b5

test:
  secret_key_base: 5d49d3f1838998489196f37378d38b0704f8643f74701063990866d5bf92d2cde04323f5bfd7884404f1cabca1cf2cb8fccd3f089c3a3a318d2e86fc238da70f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
